[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", url="https://api.arbiscan.io/api" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", url="https://api-sepolia.arbiscan.io/api"}